### ISSUE TITLE
NullPointerException if there is no field named "Description" in jira

### ISSUE THREAD

**Issue by Ruschnik** [serenity-bdd/serenity-jira#33]
Narrative:
As a test developer 
I want to use a field "Beschreibung" in the stories in JIRA 
In order to describe my story there.
Scenario:
Given there is an field "Beschreibung" configured for stories in JIRA but no field named "Description"
And I set jira.custom.narrative.field=Beschreibung 
When I start the test
Then I see the text of field "Beschreibung" in my serenity report
;-)
But instead I get a NullPointerException:
```
|2016-04-29 13:36:24,273| [pool-8-thread-3] ERROR  net.thucydides.core.requirements.RequirementsTagProvider Tag provider failure
java.lang.NullPointerException: use Optional.orNull() instead of Optional.or(null)
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
        at com.google.common.base.Present.or(Present.java:48)
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.narativeTextFrom(JIRARequirementsProvider.java:200)
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.requirementFrom(JIRARequirementsProvider.java:184)
        at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:281)
        at net.thucydides.core.requirements.RequirementsServiceImplementation.getParentRequirementOf(RequirementsServiceImplementation.java:184)
        at net.thucydides.core.requirements.RequirementsServiceImplementation.getParentRequirementFor(RequirementsServiceImplementation.java:129)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:129)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:123)
        at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:86)
        at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:213)
        at net.thucydides.core.reports.ReportService.access$100(ReportService.java:26)
        at net.thucydides.core.reports.ReportService$1.run(ReportService.java:148)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
The reason seems to be that the method Present::or(default : Present) has a strange precondition: the Parameter "default" must not be `null`. But it is `null` for the call
`customFieldNameFor(issue, customFieldName.get()).or(issue.getRendered().getDescription())` if there is no field named "Description"

By the way: do I have to add `serenity-jira-plugin` to the dependencies in my POM?

**Comment by YamStranger** [comment]
@Ruschnik 
Thanks for this issue, fix will be available in next release!

**Comment by Ruschnik** [comment]
NullPointerException is fixed. But now the description of the story in the report is empty. I changed the method

`private String narativeTextFrom(IssueSummary issue)`
(locally) to
```
    private String narativeTextFrom(IssueSummary issue) {
        Optional<String> customFieldName = Optional.fromNullable(environmentVariables.getProperty(JIRA_CUSTOM_NARRATIVE_FIELD.getName()));
        if (customFieldName.isPresent()) {
            return issue.getRendered().customField(customFieldName.get()).or(ObjectUtils.firstNonNull(issue.getRendered().getDescription(), ""));
        } else {
            return issue.getRendered().getDescription();
        }
    }
```
But it did not help. 
Of course I do not understand how all this `issue.getRendered().custumField()` and `issue.customField()` works anyway ;-)

**Comment by YamStranger** [comment]
Hello @Ruschnik 
If description is empty - is should be empty in report without nullpointer, if it is not empty - it should be filled in report. 

Did you expect some default value for description, in case if such filed is abscond?

**Comment by Ruschnik** [comment]
Hello @YamStranger 

Thanks for your help.
No, empty string as default value is OK. But I cannot see the text of the description ("Beschreibung") of the user story in the report. (I can see the title of the story in the report (differs from the title of the story file)). But maybe something is wrong with our test environment (jira, security, browser settings) at work. Some tests for serenity-jira failed because of security problems. And it was even hard to use gradle. So I am not sure what is going wrong at the moment. Have you checked whether the feature given by "jira.custom.narrative.field" works for you? Maybe I can test it as well from home using your (wakaleos) jira (no jira at home).

**Comment by YamStranger** [comment]
Hello @Ruschnik 

I checked, this case covered in our test: 

https://github.com/serenity-bdd/serenity-jira/blob/4193f52f692b11ab5408857c9cea7123f33059c5/serenity-jira-requirements-provider/src/test/groovy/net/serenitybdd/plugins/jira/WhenReadingStoriesFromJira.groovy#L56

so description is retrieved from jira.

**Comment by Ruschnik** [comment]
Hello  @YamStranger 

OK. But if I run serenity-behave with `serenity-ira-requirements-provider version 1.1.1` and 
my story file contains `@issue DEMO-224`, 
my serenity.properties contain `jira.url = https://wakaleo.atlassian.net, jira.project = DEMO`
and also `jira.custom.narrative.field=HipChat discussions`
then in my serenity report I see the description of field "description" and not the text of "HipChat discussions". 
But I close this issue because this is not related to a NullPointerException any longer.
