### ISSUE TITLE
Issue in Jira-Thucydides integration

### ISSUE THREAD

**Issue by ksyedalibe** [serenity-bdd/serenity-jira#57]
I am trying to integrate Jira with Thucydides. Below are version details:

<thucydides.version>0.9.268</thucydides.version>
<thucydides.jira.version>0.9.268</thucydides.jira.version>

While executing the thucydides stories  i am getting the below err. could you please let me know how to fix this? Also i am wondering that this (rpc/soap/jirasoapservice-v2) is appending with jira url automatically (not sure why?)

SEVERE: RuntimeException while executing runnable net.thucydides.plugins.jira.JiraListener$2@4f8c5fe7 with executor com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService@6daa7411
net.thucydides.plugins.jira.model.IssueTrackerUpdateException: Could not update JIRA using URL (https://www.***.com/jira/browse/**rpc/soap/jirasoapservice-v2**)
	at net.thucydides.plugins.jira.service.JiraIssueTracker.processJiraException(JiraIssueTracker.java:78)
	at net.thucydides.plugins.jira.service.JiraIssueTracker.getCommentsFor(JiraIssueTracker.java:102)
	at net.thucydides.plugins.jira.JiraListener.newOrUpdatedCommentFor(JiraListener.java:239)

**Comment by ksyedalibe** [comment]
Found the Solution as Jira 6.X version only will support Thucydides. Since we are using Jira 7.x version we unable to connect it.hence we upgraded to Serenity 1.X version to connecting Jira
