### ISSUE TITLE
Epics and Stories Tab in serenity report is not getting displayed 

### ISSUE THREAD

**Issue by SerTest3** [serenity-bdd/serenity-jira#88]
Previously Epics and Stories tab were displayed in Serenity report. Currently its not getting displayed. 

I see the below error while building the pom.xml 

net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByJQL(JerseyJiraClient.java:128) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getRequirements(JIRARequirementsProvider.java:114) [serenity-jira-requirements-provider-1.8.0.jar:?]
	at net.thucydides.core.requirements.RequirementsProvided.by(RequirementsProvided.java:15) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.requirements.MultiSourceRequirementsService.getRequirements(MultiSourceRequirementsService.java:46) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.requirements.BaseRequirementsService.getRequirementTypes(BaseRequirementsService.java:186) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:162) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:109) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:255) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:32) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:186) [serenity-core-1.8.19.jar:1.8.19]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.NullPointerException
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToComment(JerseyJiraClient.java:300) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.commentsIn(JerseyJiraClient.java:290) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToIssueSummary(JerseyJiraClient.java:279) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByJQLBatches(JerseyJiraClient.java:153) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.FindByJQLLoaderUsingBatches.load(FindByJQLLoaderUsingBatches.java:17) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.FindByJQLLoaderUsingBatches.load(FindByJQLLoaderUsingBatches.java:8) ~[serenity-jira-plugin-1.8.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986) ~[guava-20.0.jar:?]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByJQL(JerseyJiraClient.java:124) ~[serenity-jira-plugin-1.8.0.jar:?]
	... 14 more
2018-06-26 15:04:39,347 DEBUG JIRARequirementsProvider [pool-7-thread-2] Loading root requirements done: 0
2018-06-26 15:04:39,352 DEBUG ConcurrentRequirementsLoader [pool-7-thread-2] Loading 0 requirements
2018-06-26 15:04:39,352 DEBUG RequirementsTagProvider [pool-7-thread-2] Requirements found:[]
2018-06-26 15:04:39,353 DEBUG JIRARequirementsProvider [pool-7-thread-2] Find parent requirement in JIRA for SmokeTest for Taxation Event APM
2018-06-26 15:04:39,516 DEBUG JIRARequirementsProvider [pool-7-thread-1] No root requirements found (JQL = issuetype = epic and project=GRK
net.serenitybdd.plugins.jira.model.JQLException: java.lang.NullPointerException
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByJQL(JerseyJiraClient.java:128) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getRequirements(JIRARequirementsProvider.java:114) [serenity-jira-requirements-provider-1.8.0.jar:?]
	at net.thucydides.core.requirements.RequirementsProvided.by(RequirementsProvided.java:15) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.requirements.MultiSourceRequirementsService.getRequirements(MultiSourceRequirementsService.java:46) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.requirements.BaseRequirementsService.getRequirementTypes(BaseRequirementsService.java:186) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:162) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:109) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:255) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:32) [serenity-core-1.8.19.jar:1.8.19]
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:186) [serenity-core-1.8.19.jar:1.8.19]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.NullPointerException
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToComment(JerseyJiraClient.java:300) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.commentsIn(JerseyJiraClient.java:290) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.convertToIssueSummary(JerseyJiraClient.java:279) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByJQLBatches(JerseyJiraClient.java:153) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.FindByJQLLoaderUsingBatches.load(FindByJQLLoaderUsingBatches.java:17) ~[serenity-jira-plugin-1.8.0.jar:?]
	at net.serenitybdd.plugins.jira.client.FindByJQLLoaderUsingBatches.load(FindByJQLLoaderUsingBatches.java:8) ~[serenity-jira-plugin-1.8.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057) ~[guava-20.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986) ~[guava-20.0.jar:?]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByJQL(JerseyJiraClient.java:124) ~[serenity-jira-plugin-1.8.0.jar:?]

Kindly provide your thoughts on this issue

**Comment by SerTest3** [comment]
Team, 

Any solution for this issue ?

**Comment by majucamex2005** [comment]
John Ferguson your answer was an Epic!!!! lol
