### ISSUE TITLE
301 erorr thrown when trying to update Jira via Serenity BDD

### ISSUE THREAD

**Issue by annmcd** [serenity-bdd/serenity-jira#94]
**We have a valid epic  eg the folloiwng query is valid in Jira
issuetype = epic AND project =SAL  

OUR SERENITY PROEPRTIES ARE** 
serenity.requirements.types=capability,feature,story
jira.url=http://mycompany.atlassian.net
jira.project=SAL
jira.username=myusername
jira.password=mypassword
serenity.public.url=file:///C:/workspace4/SFTestPack/target/site/serenity/
show.pie.charts=true
serenity.jira.workflow.active=true
serenity.jira.workflow=jira-workflow.groovy
serenity.proxy.http=myproxyserver
serenity.proxy.http_port=8080

OUR pom.xml contains <dependencies>
    <dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-common</artifactId>
    <version>2.25.1</version>
  </dependency>
    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-jira-requirements-provider</artifactId>
      <version>1.11.0</version>
    </dependency>
 <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-jira-plugin</artifactId>
      <version>1.9.0</version>
    </dependency>
    <dependency>
      <groupId>com.googlecode.lambdaj</groupId>
      <artifactId>lambdaj</artifactId>
      <version>2.3.3</version>
    </dependency>
    <dependency>
      <groupId>com.opencsv</groupId>
      <artifactId>opencsv</artifactId>
      <version>${opencsv.version}</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>${com.microsoft.sqlserver.version}</version>
    </dependency>
    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-core</artifactId>
      <version>2.0.32</version>
    </dependency>
    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-cucumber</artifactId>
      <version>1.9.23</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>${selenium.webdriver.version}</version>
    </dependency>
    
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.5</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.1.2</version>
    </dependency>
    
  </dependencies>
  <build>
    <defaultGoal>validate</defaultGoal>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.5</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <encoding>${project.build.sourceEncoding}</encoding>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <testSource>${java.version}</testSource>
          <testTarget>${java.version}</testTarget>
          <showDeprecation>true</showDeprecation>
          <showWarnings>true</showWarnings>
          <fork>true</fork>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.18</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>net.serenity-bdd.maven.plugins</groupId>
        <artifactId>serenity-maven-plugin</artifactId>
        <version>2.0.32</version>
       
        <executions>
          <execution>
            <id>serenity-reports</id>
            <phase>post-integration-test</phase>
            <goals>
              <goal>aggregate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>2.18</version>

        <configuration>
          <includes>
            <include>${serenity-include1}</include>
            <include>${serenity-include2}</include>
            <include>${serenity-include3}</include>
          </includes>
          <systemProperties>
            
            <webdriver.driver>${webdriver.driver}</webdriver.driver>
            <target_cle_environment>${target_cle_environment}</target_cle_environment>
          </systemProperties>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>
</project>

**JIRA IS NOT BEING UPDATED WHEN ISSUING MVN VERIFY A 301 IS THROWN**

[net.thucydides.core.requirements.RequirementsTagProvider:28] - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
java.lang.IllegalArgumentException: net.serenitybdd.plugins.jira.model.JQLException: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:266) ~[serenity-jira-requirements-provider-1.11.0.jar:na]
	at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26) ~[serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:156) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementFor(BaseRequirementsService.java:61) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:168) [serenity-reports-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:162) [serenity-reports-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:106) [serenity-reports-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175) [serenity-model-2.0.32.jar:2.0.32]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
Caused by: net.serenitybdd.plugins.jira.model.JQLException: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:251) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:255) ~[serenity-jira-requirements-provider-1.11.0.jar:na]
	... 13 common frames omitted
Caused by: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.checkValid(JerseyJiraClient.java:574) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.readFieldValues(JerseyJiraClient.java:501) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByKey(JerseyJiraClient.java:257) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:17) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:8) ~[serenity-jira-plugin-1.9.0.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3948) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957) ~[guava-25.0-jre.jar:na]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:247) ~[serenity-jira-plugin-1.9.0.jar:na]
	... 14 common frames omitted
[WARN ] 2019-01-16 15:11:54,409 [pool-10-thread-2] [net.thucydides.core.requirements.RequirementsTagProvider:28] - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
java.lang.IllegalArgumentException: net.serenitybdd.plugins.jira.model.JQLException: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:266) ~[serenity-jira-requirements-provider-1.11.0.jar:na]
	at net.thucydides.core.requirements.ParentRequirementsProvided.forOutcome(ParentRequirementsProvided.java:26) ~[serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementOf(BaseRequirementsService.java:156) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.requirements.BaseRequirementsService.getParentRequirementFor(BaseRequirementsService.java:61) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addParentRequirmentFieldToContext(HtmlAcceptanceTestReporter.java:168) [serenity-reports-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:162) [serenity-reports-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:106) [serenity-reports-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175) [serenity-model-2.0.32.jar:2.0.32]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
Caused by: net.serenitybdd.plugins.jira.model.JQLException: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:251) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getParentRequirementOf(JIRARequirementsProvider.java:255) ~[serenity-jira-requirements-provider-1.11.0.jar:na]
	... 13 common frames omitted
Caused by: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.checkValid(JerseyJiraClient.java:574) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.readFieldValues(JerseyJiraClient.java:501) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.loadByKey(JerseyJiraClient.java:257) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:17) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.client.FindByKeyLoader.load(FindByKeyLoader.java:8) ~[serenity-jira-plugin-1.9.0.jar:na]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3948) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972) ~[guava-25.0-jre.jar:na]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957) ~[guava-25.0-jre.jar:na]
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByKey(JerseyJiraClient.java:247) ~[serenity-jira-plugin-1.9.0.jar:na]
	... 14 common frames omitted
[WARN ] 2019-01-16 15:11:54,409 [pool-10-thread-3] [net.thucydides.core.requirements.RequirementsTagProvider:28] - Failed to load requirements: net.serenitybdd.plugins.jira.model.JQLException: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301

**Comment by annmcd** [comment]
The following trace might additional information as to what the issue is. Thanking you  in advance
[DEBUG] 2019-01-16 16:33:28,370 [main] [net.thucydides.core.reports.ReportService:182] - Shutting down executor service
[DEBUG] 2019-01-16 16:33:28,370 [main] [net.thucydides.core.reports.ReportService:186] - Reports generated in: 1399 ms
[DEBUG] 2019-01-16 16:33:28,370 [main] [net.thucydides.core.reports.ReportService:163] - Generating reports for 1 test outcomes using: net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@17273273
[DEBUG] 2019-01-16 16:33:28,371 [pool-7-thread-1] [net.thucydides.core.reports.ReportService:174] - Processing test outcome Validate CSV Structure:Verify that data is in csv file corresponds to the data in the database for an entity
[DEBUG] 2019-01-16 16:33:28,371 [main] [net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter:37] - GENERATING JUNIT REPORTS
[DEBUG] 2019-01-16 16:33:28,371 [pool-7-thread-1] [net.thucydides.core.reports.ReportService:237] - net.thucydides.core.reports.html.HtmlAcceptanceTestReporter@17273273: Generating report for test outcome: Validate CSV Structure:Verify that data is in csv file corresponds to the data in the database for an entity
[DEBUG] 2019-01-16 16:33:28,372 [pool-7-thread-1] [net.thucydides.core.reports.html.HtmlAcceptanceTestReporter:99] - GENERATE TEST OUTCOME REPORT FOR Verify that data is in csv file corresponds to the data in the database for an entity in 1a43da7609c516e8fbe9f10dda2528140dc259e746285cdcbfc6aa2dd48c7497
[DEBUG] 2019-01-16 16:33:28,410 [pool-7-thread-1] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider:96] - JIRA URL: http://canadalifeeurope.atlassian.net
[DEBUG] 2019-01-16 16:33:28,410 [pool-7-thread-1] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider:97] - JIRA project: SAL
[DEBUG] 2019-01-16 16:33:28,411 [pool-7-thread-1] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider:98] - JIRA user: ann.mcdonald@canadalife.de
[DEBUG] 2019-01-16 16:33:28,672 [pool-7-thread-1] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider:112] - Loading root requirements: issuetype = epic and project=SAL
[DEBUG] 2019-01-16 16:33:32,161 [pool-7-thread-1] [net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider:116] - No root requirements found (JQL = issuetype = epic and project=SAL
net.serenitybdd.plugins.jira.model.JQLException: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
	at net.serenitybdd.plugins.jira.client.JerseyJiraClient.findByJQL(JerseyJiraClient.java:141) ~[serenity-jira-plugin-1.9.0.jar:na]
	at net.serenitybdd.plugins.jira.requirements.JIRARequirementsProvider.getRequirements(JIRARequirementsProvider.java:114) ~[serenity-jira-requirements-provider-1.11.0.jar:na]
	at net.thucydides.core.requirements.RequirementsProvided.by(RequirementsProvided.java:15) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.requirements.MultiSourceRequirementsService.getRequirements(MultiSourceRequirementsService.java:40) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.requirements.BaseRequirementsService.getRequirementTypes(BaseRequirementsService.java:203) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.addTestOutcomeToContext(HtmlAcceptanceTestReporter.java:160) [serenity-reports-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:106) [serenity-reports-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:239) [serenity-model-2.0.32.jar:2.0.32]
	at net.thucydides.core.reports.ReportService.lambda$generateReportsFor$0(ReportService.java:175) [serenity-model-2.0.32.jar:2.0.32]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
Caused by: net.serenitybdd.plugins.jira.model.JQLException: JIRA query failed: error 301
