### ISSUE TITLE
 Provider net.serenitybdd.plugins.jira.JiraStepListener could not be instantiated

### ISSUE THREAD

**Issue by lilyhoang** [serenity-bdd/serenity-jira#98]
Please help to check this issue 

[main] ERROR net.thucydides.core.steps.StepEventBus - Could not instantiate listener 
java.util.ServiceConfigurationError: net.thucydides.core.steps.StepListener: Provider net.serenitybdd.plugins.jira.JiraStepListener could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at net.thucydides.core.steps.StepEventBus.getCustomListeners(StepEventBus.java:199)
	at net.thucydides.core.steps.StepEventBus.getAllListeners(StepEventBus.java:184)
	at net.thucydides.core.steps.StepEventBus.testSuiteStarted(StepEventBus.java:239)
	at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:176)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$0(SerenityReporter.java:129)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:132)
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:315)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:66)
	at net.serenitybdd.cucumber.CucumberWithSerenity.<init>(CucumberWithSerenity.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NoClassDefFoundError: ch/lambdaj/function/convert/Converter
	at net.serenitybdd.plugins.jira.JiraStepListener.<init>(JiraStepListener.java:47)
	at net.serenitybdd.plugins.jira.JiraStepListener.<init>(JiraStepListener.java:51)
	at sun.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 29 more
Caused by: java.lang.ClassNotFoundException: ch.lambdaj.function.convert.Converter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more

**Comment by AlexChernookov** [comment]
> Please help to check this issue
> 
> [main] ERROR net.thucydides.core.steps.StepEventBus - Could not instantiate listener
> java.util.ServiceConfigurationError: net.thucydides.core.steps.StepListener: Provider net.serenitybdd.plugins.jira.JiraStepListener could not be instantiated
> at java.util.ServiceLoader.fail(ServiceLoader.java:232)
> at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
> at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
> at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
> at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
> at net.thucydides.core.steps.StepEventBus.getCustomListeners(StepEventBus.java:199)
> at net.thucydides.core.steps.StepEventBus.getAllListeners(StepEventBus.java:184)
> at net.thucydides.core.steps.StepEventBus.testSuiteStarted(StepEventBus.java:239)
> at cucumber.runtime.formatter.SerenityReporter.handleTestSourceRead(SerenityReporter.java:176)
> at cucumber.runtime.formatter.SerenityReporter.lambda$new$0(SerenityReporter.java:129)
> at cucumber.runner.EventBus.send(EventBus.java:28)
> at cucumber.runtime.model.CucumberFeature.sendTestSourceRead(CucumberFeature.java:132)
> at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:315)
> at cucumber.api.junit.Cucumber.(Cucumber.java:66)
> at net.serenitybdd.cucumber.CucumberWithSerenity.(CucumberWithSerenity.java:39)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
> at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
> at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
> at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
> at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
> at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
> at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
> at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
> at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
> at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
> at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
> at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
> Caused by: java.lang.NoClassDefFoundError: ch/lambdaj/function/convert/Converter
> at net.serenitybdd.plugins.jira.JiraStepListener.(JiraStepListener.java:47)
> at net.serenitybdd.plugins.jira.JiraStepListener.(JiraStepListener.java:51)
> at sun.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> at java.lang.Class.newInstance(Class.java:442)
> at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
> ... 29 more
> Caused by: java.lang.ClassNotFoundException: ch.lambdaj.function.convert.Converter
> at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ... 36 more
I had the same issue in some of serenity group there was workaround for this. Just try to add dependency in your pom file         
<dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>

Hope it will fix the issue
